empleados/applications/persona/urls.py
from django.urls import path

from . import views

# personas:<<name_path>>
urls_personas = ([

                     path(route='', view=views.InitView.as_view(), name='inicio'),

                     path(route='listar-empleados', view=views.ListAllPersonas.as_view(), name='personas-all'),
                     path(route='success', view=views.SuccessViews.as_view(), name='success'),
                     path(route='crear-empleado', view=views.CreatePersonaView.as_view()),
                     path(route='actualizar-empleado/<int:pk>', view=views.UpdateEmpleadoView.as_view(), name='update'),
                     path(route='eliminar-empleado/<int:pk>', view=views.DeleteEmpleadoView.as_view(), name='delete'),
                     path(route='detalle-empleado/<int:pk>', view=views.DetailPersonaView.as_view(), name='detalle-empleado'),
                     path(route='listar-habilidades-empleados/<int:id>', view=views.ListHabilidadesPersona.as_view()),
                     path(route='buscar-empleados', view=views.ListAllPersonasByKWord.as_view(), name='buscar-persona-by-kword'),
                     path(route='listar-empleados-por-area/<str:departamento>',
                          view=views.ListAllPersonasByArea.as_view()),
                 ], "personas")

empleados/empleados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from applications.departamento.urls import url_departameto
from applications.home.urls import urls_home
from applications.persona.urls import urls_personas

urlpatterns = [
    path('admin/', admin.site.urls),

    # Incluimos las urls de app departamento
    path('', include(url_departameto)),
    # Home
    path('', include(urls_home)),
    # Persona
    path('', include(urls_personas))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# // extiende las urls que se generan automaticamente espeficando la url de setting y la carpeta condetendora
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Adding the debug query in dashboard admin
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path(r'^__debug__/', include(debug_toolbar.urls))
                  ] + urlpatterns

empleados/applications/persona/models.py
from django.db import models

from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField


class Habilidades(models.Model):
    hability = models.CharField(verbose_name='Habilidad', max_length=50)

    class Meta:
        # Nombre a mostrar en el dashboard
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'

    def __str__(self):
        return f"{self.id} | {self.hability}"


class Persona(models.Model):
    """ Modelo para tabla empleado  """""
    first_name = models.CharField(verbose_name='Nombres', max_length=50)
    last_name = models.CharField(verbose_name='Apellidos', max_length=50)
    nickname = models.CharField(verbose_name='Apodo generado automaticamente', max_length=100, blank=True, null=True)

    # Creando similar a un Enum y solo permita valores permitidos
    # En el admin se mostrara como una select html
    JOB_CHOICES = [
        ('1', 'CONTADOR'),
        ('2', 'ADMINISTRADOR'),
        ('3', 'ECONOMIESTA'),
        ('4', 'OTRO'),
    ]

    job = models.CharField(verbose_name='Trabajos', max_length=50, choices=JOB_CHOICES)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)

    # Creando la relacion y campo con el modelo departamento
    # relacion de uno a muchos
    departamento = models.ForeignKey(to=Departamento, on_delete=models.CASCADE)

    # relacion muchos a muchos
    habilities = models.ManyToManyField(Habilidades)

    curriculum_vitae = RichTextField(verbose_name='Hoja de vida', null=True, blank=True)

    class Meta:
        # Nombre a mostrar en el dashboard
        verbose_name = 'Personal'
        verbose_name_plural = 'Mi Personal'
        # Ordenamiento
        ordering = ['-first_name']
        # Permite validar convinaciones de cambos y verificar que esa conbinacion no se repita
        unique_together = ('first_name', 'last_name')

    def __str__(self):
        return f"{self.id} | {self.first_name} | {self.last_name} | {self.job} | {self.departamento}"

empleados/applications/persona/views.py
from django.shortcuts import render
from django.views.generic import (ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView)
from .models import Persona
from django.urls import reverse_lazy


# Create your views here.
class ListAllPersonas(ListView):
    model = Persona
    template_name = 'personas/list_all.html'
    # define el nombre de variable a enviar al html
    # si no se especifica el content, se retornara la data en la variable object_list al template
    context_object_name = 'personas'

    # Paginacion
    # Recibe el valor a mostrar por peticion, y por get capturara automaticamente el page
    paginate_by = 2


class ListAllPersonasByArea(ListView):
    """ Lista de personas por area """
    model = Persona
    template_name = 'personas/list_all.html'
    # define el nombre de variable a enviar al html
    # si no se especifica el content, se retornara la data en la variable object_list al template
    context_object_name = 'personas'

    """
    # departamento__name // Departamento.name
    queryset = Persona.objects.filter(
        departamento__name = 'tecnologia'
    )"""

    # Funcion que tiene la logica de reemplazo para consultar sobre la bd
    def get_queryset(self):
        # accediendo a los valores enviados por la url y definidos en esta
        departamento = self.kwargs['departamento']

        data = Persona.objects.filter(
            departamento__name=departamento
        )
        return data


class ListAllPersonasByKWord(ListView):
    """Lista de empleados por palabta clave"""
    template_name = 'personas/list_all.html'
    context_object_name = 'personas'

    def get_queryset(self):
        # Capturando por get el parametro ?kword
        key_word = self.request.GET.get('kword')
        print("key_word >>", key_word)
        data = Persona.objects.filter(
            first_name=key_word
        )
        return data


class ListHabilidadesPersona(ListView):
    template_name = 'personas/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        # accediendo a los valores enviados por la url y definidos en esta
        id = self.kwargs['id']
        # Recuperando un unico registro de persona
        persona = Persona.objects.get(id=id)
        # Accediendo a la relacion directa del modelo Persona con habiltiies
        habilidades = persona.habilities.all()
        return habilidades


class DetailPersonaView(DetailView):
    model = Persona
    context_object_name = 'persona'
    template_name = 'personas/detail_persona.html'

    # Enviando mas variables al template, se debe sobreescribir el metodo
    def get_context_data(self, **kwargs):
        context = super(DetailPersonaView, self).get_context_data(**kwargs)
        print("context detail >>", context)
        # Añadiendo al contexto al html
        context['titulo'] = 'Empleado del mes'

        return context


class CreatePersonaView(CreateView):
    model = Persona
    template_name = 'personas/add.html'
    # Indicarle que atributos del modelo se permitiran pintar y actualizar
    # fields = ('__all__') # permite generar todos los campos
    fields = ['first_name', 'last_name', 'job', 'departamento', 'habilities']

    # Define a donde se debe redirigir cuando se complete el proceso
    # usando reverse_lazy se le pasa el nombre de la url
    success_url = reverse_lazy(viewname='personas:success')

    # sobrescribiendo el metodo despues de guardarlo, para adicionar el valor en la nueva columna
    def form_valid(self, form):
        print(type(form))
        # Ya se guardo el registro y retorna una instancia del modelo
        empleado = form.save()
        # Modificando la propiedad
        empleado.nickname = empleado.first_name[0:2] + '-' + empleado.last_name[0:2]
        # Guardando nuevamente el modelo
        empleado.save()
        return super(CreatePersonaView, self).form_valid(form)


class SuccessViews(TemplateView):
    template_name = 'personas/success.html'


class UpdateEmpleadoView(UpdateView):
    template_name = 'personas/update.html'
    model = Persona
    # fields = ('__all__')  # permite generar todos los campos
    fields = ['first_name', 'last_name', 'job', 'departamento', 'habilities']
    success_url = reverse_lazy(viewname='personas:success')

    # Sobrescribe el metodo antes de validar los datos
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print("****************************")
        print("request.POST >> ", request.POST)
        return super(UpdateEmpleadoView, self).post(request, *args, **kwargs)


class DeleteEmpleadoView(DeleteView):
    model = Persona
    # Template que es usado para confirmar la eliminacion
    template_name = 'personas/delete.html'
    success_url = reverse_lazy(viewname='personas:success')


class InitView(TemplateView):
    """View load init page"""
    template_name = 'personas/inicio.html'

empleados/templates/personas/add.html
<h1>Crear persona</h1>
<form method="POST" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Crear">
</form>

empleados/templates/personas/by_kword.html
<h1>Buscar empleados por palabra clave</h1>

<form action="" method="get">
    {% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese el primer nombre a buscar">
    <input type="submit" value="Buscar">
</form>

{% if personas %}
    <h1>Lista de empleados</h1>
    <ul>
        {% for persona in personas %}
            <li>{{ persona.first_name }}</li>
        {% endfor %}
    </ul>
{% endif %}

empleados/templates/personas/delete.html
<h1>Eliminada la persona</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Eliminar">
</form>

empleados/templates/personas/detail_persona.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ persona.first_name }}{% endblock title %}

{% block body %}
{% comment %}Header{% endcomment %}
{% include 'includes/header.html' %}

<div class="container">

    {% comment %}titulo // variable de contexto adicionada{% endcomment %}
    <h3>Todos los datos | {{ titulo }}</h3>

    {% comment %}  {{ persona.avatar.url }}{% endcomment %}
    <div class="container">
        <div class="col-12">
            <div class="card" style="width: 18rem;">
                {% if persona.avatar %}
                    <img src="{{ persona.avatar.url }}" class="card-img-top"
                         alt="{{ persona.first_name }} {{ persona.last_name }}">
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ persona.first_name }} {{ persona.last_name }}</h5>
                    {% comment %}.get_job_display // permite traer el valor en un campo Choice{% endcomment %}
                    <p class="card-text">Job: {{ persona.get_job_display }}.</p>
                    <p class="card-text">Departamento: {{ persona.departamento.short_name }}.</p>
                    <hr>
                    <p>Habilidades:</p>
                    <ul>
                    {% comment %} Accede a la relacion many to many  y con all devueleve todo el objeto {% endcomment %}
                        {% for habilidad in persona.habilities.all %}
                        <li>{{ habilidad.hability }}</li>
                        {% endfor %}
                    </ul>

                </div>
            </div>
        </div>
    </div>

    <hr>
    {{ persona }}
</div>
{% endblock body %}

empleados/templates/personas/habilidades.html
<h1>Lista de habilidades</h1>
<ul>
    {% for habilidad in habilidades %}
        <li>{{ habilidad }}</li>
    {% endfor %}
</ul>
{{ habilidades }}

empleados/templates/personas/inicio.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Inicio Personas{% endblock title %}



{% block body %}
    {% comment %}Header{% endcomment %}
    {% include 'includes/header.html' %}

    {% comment %}Banner{% endcomment %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{% static 'img/bg-1.jpg' %}" class="d-block w-100">
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>


    {% comment %}Bloque de bienvenid{% endcomment %}
    <div class="row">
        <div class="col-12 p-5">
            <div class="text-center">
                <h1>Bienvenido al sistema de ingreso de eprsonal</h1>
                <p>Mensaje de bienvenida</p>
            </div>
        </div>
    </div>
{% endblock body %}

empleados/templates/personas/list_all.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Todo el personal{% endblock title %}



{% block body %}
    {% comment %}Header{% endcomment %}
    {% include 'includes/header.html' %}

    <div class="container">
        <h1>Lista de personas</h1>
        <div class="row mb-5">
            <div class="col-12">
                <form action="{% url 'personas:buscar-persona-by-kword' %}" method="get">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-9">
                            <input type="text"
                                   class="form-control"
                                   id="kword"
                                   name="kword" placeholder="Ingrese el primer nombre a buscar">
                        </div>
                        <div class="col-3">
                            <input type="submit" class="btn  btn-primary" value="Buscar">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>first_name</th>
                        <th>last_name</th>
                        <th>nickname</th>
                        <th>options</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for persona in personas %}
                        <tr>
                            <td>{{ persona.id }}</td>
                            <td>{{ persona.first_name }}</td>
                            <td>{{ persona.last_name }}</td>
                            <td>{{ persona.nickname }}</td>
                            <td>
                                <a class="btn btn-outline-dark"
                                   href="{% url 'personas:detalle-empleado' persona.id %}"
                                >Ver</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </div>
        </div>

        {% comment %}Si existe la paginacion{% endcomment %}
        {% if is_paginated %}
            <div class="row">
                <div class="col-12">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if page_object.has_previous %}
                                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                            {% endif %}


                            {% comment %}pagination.page_range // trae el numero de las paginas{% endcomment %}
                            {% for page in pagination.page_range %}
                                <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                            {% endfor %}
                        </ul>
                    </nav>
                </div>
            </div>
        {% endif %}

    </div>
{% endblock body %}

empleados/templates/personas/success.html
<h1>Se creo correctamente</h1>

empleados/templates/personas/update.html
<h1>Modificar datos persona</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Actualizar">
</form>